apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    env: dev
    team: backend
spec:
  selector:
    env: dev
    team: backend
    version: test
  # type: ClusterIP # default value
  ports:
    - port: 8080 # Service Port
      targetPort: 80 # Application Container running port