apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  labels:
    env: dev
    team: backend
    version: test
spec:
  containers:
    - name: nginx-deployment
      image: nginx:latest
      ports:
        - containerPort: 80
